# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4023195ccc0e9dbb2d2cadc728b89370ff2f5107ca5520bfab59a7ca4486eabb539d7e3d024cb75bd2b768350f896559b840650aa9ea4e9811fd9ba071723c41

test:
  secret_key_base: 10b23354b149a09e09ebc6ae54bbbf180bcbea0fabc48c5ea040f7d3443fa4cee87c2792f3ea460d3cf4ebb7b437714d82d9ceb4fc0e6fadf8353a56a93453e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
